### PR TITLE
Refactoring/vcr replacement

### PR DESCRIPTION
**Pull request by algodave**
The proposed solution works for testing methods that make a _single_ HTTP request via `Ethon::Easy` 

I've created a spec for the `documents_for` method but deliberately avoided to test `record_type` and `date_of_issue` properties because they're set after a second HTTP request, which when mocked returns the same JSON as the first.

So please consider this as a first draft to be refined later.

The other noticeable thing is the `reset_client` class method which is pretty ugly. I had to add it because when running more than one spec with a single command (e.g. `rake spec`) I got unpredictable behavior due to the `@@client` class variable value being kept from one test run to the other.

I would suggest a bit of refactoring on the `Sharepoint::Client`class in order to avoid the usage of class variable. I would suggest an usage like this:

``` ruby
  client = Sharepoint::Client.new(
    username: "username", 
    password: "password", 
    uri: "http://sharepoint_url"
  )
  client.documents_for path
```

That would also avoid the need of a proxy class method (e.g. `documents_for`) for each instance method (`_documents_for`), as gem users would invoke instance methods directly, (which won't need anymore the prepending `_`). 

Users of the gem would also gain the ability to connect to multiple SharePoint clients for connecting to multiple SharePoint servers.

### CODE REVIEW

**Comment by mojarra** [comment]
:+1: looks ok for me. The change of the client is ok also if you want to tackle on it. I don't know if @vjt or @lucaspiller wants to say something

**Comment by lucaspiller** [comment]
Looks good. I agree setting up the client as you propose is a better way of doing it. 👍

**Comment by lleirborras** [comment]
Looks fine to me!

**Comment by algodave** [comment]
@mojarra Please review client refactoring when you get a chance, thanks!

**Pull request merged**
